version: '3.9'

services:
  db:
    image: postgres:16
    container_name: torque_db
    restart: unless-stopped
    environment:
      POSTGRES_USER: torque
      POSTGRES_PASSWORD: torque123
      POSTGRES_DB: torque_db
    ports:
      - "5432:5432"
    volumes:
      - torque_data:/var/lib/postgresql/data
      - ./src/db/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
volumes:
  torque_data:
